### ISSUE TITLE
Metric not in Bytes

### ISSUE THREAD

**Issue by albertocastro63** [rokett/Citrix-NetScaler-Exporter#9]
I noticed that the counter Throughput is in MB, not bytes. Is it not possible to get the data in bytes? That is the best practice in Prometheus and is what is expected in general unless there is a technical reason not to follow it.

Thank you

(And thanks for the code too!)

**Comment by rokett** [comment]
Hi,

that's purely because it's how it comes out of the NetScaler; in other words I'm not doing any conversion on it and am presenting the raw NetScaler stats to Prometheus.  See https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/statistics/ns/ns/ns/ and look at the `totrxmbits` and `tottxmbits` descriptions.

Although the name of the stat suggests Mb, the description does state that it is MB hence I present it as such.

I guess we could convert the stats to bytes and feed that to Prometheus, but then it wouldn't be using the raw stats.  Do you feel strongly that it should be in bytes?

**Comment by albertocastro63** [comment]
I think it is preferable to use bytes, however in this case you do not have the raw data it may do more harm than good. I was thinking that was the problem anyway. It is up to you, probably contacting the development team for the Prometheus project may clarify things for you. I had a brief exchange with Brian Brazil that was very good.

Good luck and whatever you decide thanks for all your work.

Alberto

**Comment by rokett** [comment]
I think as the source for these particular metrics are in MB I'd prefer to leave them as-is; it makes sense to me to use whatever the raw measurement is rather than do any conversions myself.

Happy to reconsider in the future if a better argument comes along of course.

Thanks very much for your input :-)
